@startuml
hide footbox
autonumber
participant "Document Source" as DocumentSource
participant "Document Recipient" as DocumentRecipient
autonumber
activate DocumentSource
activate DocumentRecipient
DocumentSource -> DocumentRecipient : Generate Metadata (document)
DocumentRecipient -> DocumentRecipient : Extract the document
DocumentRecipient -> DocumentRecipient : Create DocumentReference from document 
DocumentRecipient --> DocumentRecipient : Create SubmissionSet from DocumentReference and context
DocumentRecipient --> DocumentRecipient : persist (e.g. XDS Provide and Register)
DocumentSource <-- DocumentRecipient : Generated DocumentReference
deactivate DocumentSource
deactivate DocumentRecipient
@enduml
