@startuml
hide footbox
participant "Document Consumer" as DocumentConsumer
participant "Document Recipient" as DocumentRecipient
activate "DocumentConsumer"
activate "DocumentRecipient"
"DocumentConsumer" -> "DocumentRecipient" : 1. Generate Metadata [ITI-106]
return
deactivate "DocumentConsumer"
deactivate "DocumentRecipient"
@enduml
