@startuml
title Provide Document Bundle [ITI-65]
hide footbox
participant "Document Source" as DocumentSource
participant "Document Recipient" as DocumentRecipient
autonumber
activate DocumentSource
activate DocumentRecipient
DocumentSource -> DocumentRecipient : Request to publish documents [ITI-65]
DocumentRecipient -> DocumentRecipient : validate content received
DocumentRecipient --> DocumentRecipient : propagate to Grouped Actor (e.g. XDS Provide and Register)
DocumentRecipient --> DocumentSource : Documents published [ITI-65]
deactivate DocumentSource
deactivate DocumentRecipient
@enduml
