@startuml
title Publish Document Bundle [ITI-105]
hide footbox
participant "Document Source" as DocumentSource
participant "Document Recipient" as DocumentRecipient
autonumber
activate DocumentSource
activate DocumentRecipient
DocumentSource -> DocumentRecipient : Request to publish document [ITI-105]
DocumentRecipient -> DocumentRecipient : Validate DocumentReference
DocumentRecipient -> DocumentRecipient : Extract the document
DocumentRecipient -> DocumentRecipient : Revise DocumentReference to point at document 
DocumentRecipient --> DocumentRecipient : Create SubmissionSet from DocumentReference and context
DocumentRecipient --> DocumentRecipient : persist (e.g. XDS Provide and Register)
DocumentRecipient --> DocumentSource : Document published [ITI-105]
deactivate DocumentSource
deactivate DocumentRecipient
@enduml
