@startuml
title Publish Document Bundle [ITI-105]
hide footbox
participant "Document Source" as DocumentSource
participant "Document Recipient" as DocumentRecipient
activate "DocumentSource"
activate "DocumentRecipient"
"DocumentSource" -> "DocumentRecipient" : 1. Request to publish document [ITI-105]
"DocumentRecipient" --> "DocumentSource" : 2. Document published [ITI-105]
deactivate "DocumentSource"
deactivate "DocumentRecipient"
@enduml
