# ╭────────────────────────────────────────────sushi-config.yaml───────────────────────────────────────────────╮
# | documentation of this sushi-config.yaml file https://fshschool.org/docs/sushi/configuration/               |
# ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
id: ihe.iti.mhd
canonical: https://profiles.ihe.net/ITI/MHD
name: IHE_ITI_MHD
version: 5.0.0-prototype
fhirVersion: 4.0.1
status: active
title: "Mobile access to Health Documents (MHD)"
description: ImplementationGuide for IHE IT Infrastructure Technical Framework Supplement Mobile access to Health Documents (MHD)
#copyright: IHE http://www.ihe.net/Governance/#Intellectual_Property
copyrightYear: 2020+
releaseLabel: ci-build
#releaseLabel: Trial-Implementation
#date: 2022-03-01
publisher:
  - name: IHE IT Infrastructure Technical Committee
  - url: https://www.ihe.net/ihe_domains/it_infrastructure/
  - email: iti@ihe.net
contact:
  - name: IHE IT Infrastructure Technical Committee
    telecom:
      - system: email
        value: iti@ihe.net
license: CC-BY-4.0
jurisdiction: 'http://unstats.un.org/unsd/methods/m49/m49.htm#001'
dependencies:
  ihe.iti.balp:
    id: iheitibasicaudit
    uri: https://profiles.ihe.net/ITI/BALP/ImplementationGuide/ihe.iti.balp
    version: 1.1.0
  ihe.formatcode.fhir:
    id: iheformatcodefhir
    uri: https://profiles.ihe.net/fhir/ihe.formatcode.fhir/ImplementationGuide/ihe.formatcode.fhir
    version: 1.1.0
 
parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
    - input/examples
#  path-pages:
#    - input/pagecontent
#    - fsh-generated/includes
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'true'
  autoload-resources: 'true'
  shownav: 'true'

# additional examples that need descriptions
resources:
  Bundle/Bundle-FindDocumentReferences:
    name: Example FindDocumentReferences response
    description: An example of a searchset Bundle with one DocumentReference
    exampleBoolean: true

# ╭────────────────────────────────────────────pages───────────────────────────────────────────────╮
# │  The pages property corresponds to IG.definition.page.                                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
pages:
  index.md:
    title: "MHD Home"
  1331_actors_and_transactions.md:
    title: "1:33.1 Actors and Transactions"
  1332_actor_options.md:
    title: "1:33.2 Actor Options"
  1333_required_grouping.md:
    title: "1:33.3 Required Grouping"
  1334_overview.md:
    title: "1:33.4 Overview"
  1335_security_considerations.md:
    title: "1:33.5 Security Considerations"
  1336_cross_profile_considerations.md:
    title: "1:33.6 Cross Profile Considerations"
  ITI-65.md:
    title: "2:3.65 Provide Document Bundle [ITI-65]"
  ITI-66.md:
    title: "2:3.66 Find Document Lists [ITI-66]"
  ITI-67.md:
    title: "2:3.67 Find Document References [ITI-67]"
  ITI-68.md:
    title: "2:3.68 Retrieve Document [ITI-68]"
  ITI-105.md:
    title: "2:3.105 Simplified Publish [ITI-105]"
  ITI-106.md:
    title: "2:3.106 Generate Metadata [ITI-106]"
  31_xds.md:
    title: "3:4.2.4.1 Error Codes"
  32_fhir_maps.md:
    title: "3:4.5 FHIR Maps"
  testplan.md:
    title: "Test Plan"
    extension: 
      - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
        valueCode: informative
  a_issues.md:
    title: "Issues"
    extension: 
      - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
        valueCode: informative
      

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided ig-data/input/includes/menu.xml file, delete the "menu" property below.     │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  MHD Home: index.html
  Volume 1: 
    Introduction: index.html
    "Actors and Transactions": 1331_actors_and_transactions.html
    "Actor Options": 1332_actor_options.html
    "Actor Required Grouping": 1333_required_grouping.html
    "Overview": 1334_overview.html
    "Security Considerations": 1335_security_considerations.html
    "Cross Profile Considerations": 1336_cross_profile_considerations.html
  Volume 2:
    "Provide Document Bundle [ITI-65]": ITI-65.html
    "Find Document Lists [ITI-66]": ITI-66.html
    "Find Document References [ITI-67]": ITI-67.html
    "Retrieve Document [ITI-68]": ITI-68.html
    "Simplified Publish [ITI-105]": ITI-105.html
    "Generate Metadata [ITI-106]": ITI-106.html
  Volume 3:
    "Error Codes": 31_xds.html
    "FHIR Maps": 32_fhir_maps.html
  Test Plan: testplan.html
  Artifact Index: artifacts.html
